import {
  Controller,
  Get,
  Post,
  Patch,
  Body,
  Param,
  UseGuards,
  Query,
  Req,
} from "@nestjs/common";
import { JwtAuthGuard } from "../auth/jwt-auth.guard";
import { RolesGuard } from "../auth/roles.guard";
import { InjectModel } from "@nestjs/mongoose";
import { Model } from "mongoose";
import { Payment } from "../database/schemas/payment.schema";
import { EarlyAccessAssignmentService } from "./early-access-assignment.service";

@Controller("admin")
@UseGuards(JwtAuthGuard, RolesGuard)
export class AdminUserTableController {
  private readonly earlyAccessTag = "Early Access";
  private readonly earlyAccessDurationDays = 30;
  private readonly commissionTags = [
    "Early Access",
    "Partner",
    "Internal/Test",
  ];

  constructor(
    @InjectModel("Influencer") private readonly influencerModel: Model<any>,
    @InjectModel("Brand") private readonly brandModel: Model<any>,
    @InjectModel("Photographer") private readonly photographerModel: Model<any>,
    @InjectModel("Payment") private readonly paymentModel: Model<Payment>,
    private readonly earlyAccessAssignmentService: EarlyAccessAssignmentService,
  ) {}

  private normalizeAdminTags(tags: unknown): string[] {
    if (!Array.isArray(tags)) return [];
    return Array.from(
      new Set(
        tags.map((tag) => String(tag || "").trim()).filter((tag) => !!tag),
      ),
    );
  }

  private keepSingleCommissionTag(tags: string[]): string[] {
    const normalized = this.normalizeAdminTags(tags);
    const present = this.commissionTags.filter((tag) =>
      normalized.includes(tag),
    );
    if (present.length <= 1) {
      return normalized;
    }

    const keepTag = present.includes(this.earlyAccessTag)
      ? this.earlyAccessTag
      : present[0];
    return [
      ...normalized.filter((tag) => !this.commissionTags.includes(tag)),
      keepTag,
    ];
  }

  private getEarlyAccessConfig(userType: "influencer" | "brand" | "photographer") {
    if (userType === "influencer") {
      return {
        cap: 50,
        badge: "early_access_creator",
        note: "Auto-assigned Early Access Creator (0% for 30 days)",
      };
    }
    if (userType === "photographer") {
      return {
        cap: 50,
        badge: "early_access_creator",
        note: "Auto-assigned Early Access Creator (0% for 30 days)",
      };
    }
    return {
      cap: 20,
      badge: "early_access_brand",
      note: "Auto-assigned Launch Partner Brand (0% for 30 days)",
    };
  }

  private getDefaultCommissionOverride() {
    return {
      enabled: false,
      overrideType: "discount",
      value: 0,
      validFrom: null,
      validUntil: null,
      notes: "",
      source: "",
      assignedBy: "",
      autoGenerated: false,
      assignedAt: null,
    };
  }

  private buildEarlyAccessOverride(
    config: { note: string },
    assignedBy: string,
  ) {
    const now = new Date();
    const validUntil = new Date(now);
    validUntil.setDate(validUntil.getDate() + this.earlyAccessDurationDays);

    return {
      enabled: true,
      overrideType: "fixed",
      value: 0,
      validFrom: now,
      validUntil,
      notes: config.note,
      source: "early_access_program",
      assignedBy,
      autoGenerated: true,
      assignedAt: now,
    };
  }

  @Post("early-access/auto-assign")
  async autoAssignEarlyAccess(@Req() req: any) {
    const actorId = String(
      req?.user?.userId || req?.user?.id || "system_auto_refill",
    );
    return this.earlyAccessAssignmentService.autoAssignEarlyAccess(actorId);
  }

  @Get("early-access/auto-assign/preview")
  autoAssignEarlyAccessPreview() {
    return this.earlyAccessAssignmentService.getAutoAssignPreview();
  }

  @Post("early-access/normalize-existing-tags")
  normalizeExistingCommissionTags() {
    return this.earlyAccessAssignmentService.normalizeExistingCommissionTags();
  }

  private async getActiveEarlyAccessCount(
    userType: "influencer" | "brand" | "photographer",
    badge: string,
    excludeUserId?: string,
  ): Promise<number> {
    const model =
      userType === "influencer"
        ? this.influencerModel
        : userType === "brand"
          ? this.brandModel
          : this.photographerModel;
    const now = new Date();
    const filter: Record<string, any> = {
      status: "accepted",
      isDeleted: { $ne: true },
      commissionBadge: badge,
      "commissionOverride.enabled": true,
      "commissionOverride.source": "early_access_program",
      $or: [
        { "commissionOverride.validFrom": null },
        { "commissionOverride.validFrom": { $lte: now } },
      ],
      $and: [
        {
          $or: [
            { "commissionOverride.validUntil": null },
            { "commissionOverride.validUntil": { $gte: now } },
          ],
        },
      ],
    };

    if (excludeUserId) {
      filter._id = { $ne: excludeUserId };
    }

    return model.countDocuments(filter);
  }

  @Get("influencers")
  async getInfluencers(
    @Query("status") status?: string,
    @Query("q") q?: string,
    @Query("category") category?: string,
  ) {
    const filter: any = {};
    if (status === "deleted") {
      filter.isDeleted = { $in: [true, "true"] };
    } else {
      filter.isDeleted = { $nin: [true, "true"] };
    }
    if (q) filter.q = q;
    if (category) filter.category = category;
    const influencers = await this.influencerModel
      .find(filter)
      .lean()
      .limit(100);
    await Promise.all(
      influencers.map(async (u) => {
        // Fetch latest approved payment
        u.latestPayment = await this.paymentModel
          .findOne({ userId: u._id, status: "approved" })
          .sort({ approvedAt: -1 })
          .lean();
      }),
    );
    return influencers;
  }

  @Get("brands")
  async getBrands(
    @Query("status") status?: string,
    @Query("q") q?: string,
    @Query("category") category?: string,
  ) {
    const filter: any = {};
    if (status === "deleted") {
      filter.isDeleted = { $in: [true, "true"] };
    } else {
      filter.isDeleted = { $nin: [true, "true"] };
    }
    if (q) filter.q = q;
    if (category) filter.category = category;
    const brands = await this.brandModel.find(filter).lean().limit(100);
    await Promise.all(
      brands.map(async (b) => {
        if (!b.brandLogo) b.brandLogo = [];
        if (!b.products) b.products = [];
        if (
          b.promotionalPrice === undefined &&
          (b as any).price !== undefined
        ) {
          b.promotionalPrice = (b as any).price;
        }
        // Fetch latest approved payment
        (b as any).latestPayment = await this.paymentModel
          .findOne({ userId: b._id, status: "approved" })
          .sort({ approvedAt: -1 })
          .lean();
      }),
    );
    return brands;
  }

  @Get("photographers")
  async getPhotographers(
    @Query("status") status?: string,
    @Query("q") q?: string,
    @Query("category") category?: string,
  ) {
    const filter: any = {};
    if (status === "deleted") {
      filter.isDeleted = { $in: [true, "true"] };
    } else {
      filter.isDeleted = { $nin: [true, "true"] };
    }
    if (q) filter.q = q;
    if (category) filter.skills = category;

    const photographers = await this.photographerModel
      .find(filter)
      .lean()
      .limit(100);

    await Promise.all(
      photographers.map(async (p: any) => {
        (p as any).latestPayment = await this.paymentModel
          .findOne({ userId: p._id, status: "approved" })
          .sort({ approvedAt: -1 })
          .lean();
      }),
    );

    return photographers;
  }

  @Patch("users/:type/:id/tags")
  async patchUserTags(
    @Param("type") type: string,
    @Param("id") id: string,
    @Body() body: { adminTags?: string[] },
    @Req() req: any,
  ) {
    const normalizedType = String(type || "").toLowerCase();
    let adminTags = this.keepSingleCommissionTag(
      this.normalizeAdminTags(body?.adminTags),
    );
    if (
      normalizedType !== "influencer" &&
      normalizedType !== "brand" &&
      normalizedType !== "photographer"
    ) {
      return { message: "Unsupported user type", type, id };
    }

    const userType = normalizedType as "influencer" | "brand" | "photographer";
    const model =
      userType === "influencer"
        ? this.influencerModel
        : userType === "brand"
          ? this.brandModel
          : this.photographerModel;
    const currentUser: any = await model.findById(id).lean();
    if (!currentUser) {
      return { message: "User not found", type, id };
    }

    const isPendingStatus =
      String(currentUser?.status || "").toLowerCase() === "pending";
    const isEmailVerified = !!currentUser?.isEmailVerified;
    const isMobileVerified = !!currentUser?.isMobileVerified;
    const isBlockedForPendingUnverified =
      isPendingStatus && !isEmailVerified && !isMobileVerified;
    if (isBlockedForPendingUnverified && adminTags.length > 0) {
      return {
        message:
          "Cannot assign badges/tags while user is pending and both email/mobile are unverified.",
        blocked: true,
        warnings: [
          "User is pending with email/mobile unverified. Verify at least one contact method or approve user before assigning badges/tags.",
        ],
        user: currentUser,
      };
    }

    const actorId = String(req?.user?.userId || req?.user?.id || "admin");
    const earlyAccessConfig = this.getEarlyAccessConfig(userType);
    const hasEarlyAccessTag = adminTags.includes(this.earlyAccessTag);

    const updateSet: Record<string, any> = { adminTags };
    const warnings: string[] = [];

    if (hasEarlyAccessTag) {
      if (String(currentUser?.status || "") !== "accepted") {
        adminTags = adminTags.filter((tag) => tag !== this.earlyAccessTag);
        updateSet.adminTags = adminTags;
        warnings.push("Early Access applies only to approved users.");
      } else {
        const activeCount = await this.getActiveEarlyAccessCount(
          userType,
          earlyAccessConfig.badge,
          id,
        );
        if (activeCount >= earlyAccessConfig.cap) {
          adminTags = adminTags.filter((tag) => tag !== this.earlyAccessTag);
          updateSet.adminTags = adminTags;
          warnings.push(
            userType === "brand"
              ? "Early Access cap reached (20 approved brands)."
              : "Early Access cap reached (50 approved creators).",
          );
        } else {
          updateSet.commissionBadge = earlyAccessConfig.badge;
          updateSet.commissionOverride = this.buildEarlyAccessOverride(
            earlyAccessConfig,
            actorId,
          );
        }
      }
    }

    if (!hasEarlyAccessTag) {
      const existingOverride = currentUser?.commissionOverride || {};
      const isAutoEarlyAccess =
        existingOverride?.autoGenerated === true &&
        existingOverride?.source === "early_access_program";
      if (isAutoEarlyAccess) {
        updateSet.commissionBadge = null;
        updateSet.commissionOverride = this.getDefaultCommissionOverride();
      }
    }

    const user = await model
      .findByIdAndUpdate(id, { $set: updateSet }, { new: true })
      .exec();

    if (!user) {
      return { message: "User not found", type, id };
    }

    return {
      message: warnings.length
        ? "User tags updated with constraints"
        : "User tags updated",
      warnings,
      earlyAccess: hasEarlyAccessTag
        ? {
            enabled: !!user?.commissionOverride?.enabled,
            validUntil: user?.commissionOverride?.validUntil || null,
            cap: earlyAccessConfig.cap,
          }
        : null,
      user,
    };
  }

  @Patch("users/influencer/:id/verification")
  async updateInfluencerVerification(
    @Param("id") id: string,
    @Body()
    body: {
      action?: "pending" | "approve" | "reject" | "remove";
      notes?: string;
    },
    @Req() req: any,
  ) {
    const influencer = await this.influencerModel.findById(id);
    if (!influencer) {
      return { message: "Influencer not found", id };
    }

    const action = String(body?.action || "").toLowerCase();
    const notes = String(body?.notes || "").trim();
    const actorId = String(req?.user?.userId || req?.user?.id || "admin");
    const actorRole = String(req?.user?.role || "admin");

    let status = influencer.verificationStatus || "not_submitted";
    if (action === "approve") status = "approved";
    else if (action === "reject") status = "rejected";
    else if (action === "remove") status = "removed";
    else if (action === "pending") status = "pending";

    influencer.verificationStatus = status;
    influencer.verifiedByTrendStarz = status === "approved";
    influencer.verificationAdminNotes = notes;

    const log = Array.isArray(influencer.verificationAuditLog)
      ? influencer.verificationAuditLog
      : [];
    log.push({
      action:
        action === "approve"
          ? "approved"
          : action === "reject"
            ? "rejected"
            : action === "remove"
              ? "removed"
              : notes
                ? "notes_updated"
                : "status_changed",
      status,
      note: notes,
      actorId,
      actorRole,
      actedAt: new Date(),
    });
    influencer.verificationAuditLog = log.slice(-100);

    const saved = await influencer.save();
    return { message: "Verification updated", user: saved };
  }

  @Patch("users/brand/:id/verification")
  async updateBrandVerification(
    @Param("id") id: string,
    @Body()
    body: {
      verifiedByTrendStarz?: boolean;
      adminTags?: string[];
    },
  ) {
    const brand = await this.brandModel.findById(id);
    if (!brand) {
      return { message: "Brand not found", id };
    }

    if (typeof body?.verifiedByTrendStarz === "boolean") {
      brand.verifiedByTrendStarz = !!body.verifiedByTrendStarz;
    }

    if (Array.isArray(body?.adminTags)) {
      brand.adminTags = this.normalizeAdminTags(body.adminTags);
    }

    const saved = await brand.save();
    return { message: "Brand verification updated", user: saved };
  }

  @Patch("users/:type/:id/contact-verification")
  async updateContactVerification(
    @Param("type") type: string,
    @Param("id") id: string,
    @Body()
    body: {
      isEmailVerified?: boolean;
      isMobileVerified?: boolean;
    },
  ) {
    const normalizedType = String(type || "").toLowerCase();
    if (
      normalizedType !== "influencer" &&
      normalizedType !== "brand" &&
      normalizedType !== "photographer"
    ) {
      return { message: "Unsupported user type", type, id };
    }

    const user =
      normalizedType === "influencer"
        ? await this.influencerModel.findById(id)
        : normalizedType === "brand"
          ? await this.brandModel.findById(id)
          : await this.photographerModel.findById(id);

    if (!user) {
      return { message: "User not found", type, id };
    }

    const hasEmail = typeof body?.isEmailVerified === "boolean";
    const hasMobile = typeof body?.isMobileVerified === "boolean";
    if (!hasEmail && !hasMobile) {
      return { message: "No verification fields provided", type, id };
    }

    if (hasEmail) {
      user.isEmailVerified = !!body.isEmailVerified;
    }
    if (hasMobile) {
      user.isMobileVerified = !!body.isMobileVerified;
    }

    const saved = await user.save();
    return { message: "Contact verification updated", user: saved };
  }

  // PATCH endpoint to directly update brandLogo and products for a brand
  @Patch("brands/:id/images")
  async patchBrandImages(
    @Param("id") id: string,
    @Body() body: { brandLogo?: any[]; products?: any[] },
  ) {
    const brand = await this.brandModel.findById(id);
    if (!brand) {
      return { message: "Brand not found", id };
    }
    if (body.brandLogo) {
      brand.brandLogo = body.brandLogo;
    }
    if (body.products) {
      brand.products = body.products;
    }
    await brand.save();
    return { message: "Brand images updated", brand };
  }
}
